### ISSUE TITLE
Ajouter une référence au code de conduite dans le README

### ISSUE THREAD

**Issue by chloefont** [dil-classroom/projet-coduri_fontaine_grunder_jeanrenaud#15]
Pousser à la lecture du code de conduite avant de contribuer au projet.

**Comment by Nelson-Jnrnd** [comment]
Il faudrait, également ajouter une référence au google docs du portfolio !

Voici le lien https://docs.google.com/document/d/1ma4DtP58aYvNaCOSFSOzSmjbmZ5aXtBLXJ-PQsJb1zY/edit#heading=h.39emdhizjqhs
 👍🏾
