### ISSUE TITLE
Saisie du contenu

### ISSUE THREAD

**Issue by LucaCoduriV** [dil-classroom/projet-coduri_fontaine_grunder_jeanrenaud#19]
En tant qu’utilisateur, j’aimerais pouvoir saisir du contenu dans un format de markup simplifié tel que Markdown
ou Asciidoctor qui sera compilé en HTML.

**Comment by A-Grunder** [comment]
On a décidé que la saisie de contenu sera en markdown parce que c'est un format qui nous est familier
