### ISSUE TITLE
Format des pages

### ISSUE THREAD

**Issue by LucaCoduriV** [dil-classroom/projet-coduri_fontaine_grunder_jeanrenaud#20]
En tant qu’utilisateur, j’aimerais pouvoir créer des pages contenant des métadonnées et du contenu. Par exemple, le
format suivant répondrait à ce besoin. Cet exemple est composé de deux parties : des métadonnées au format
YAML ; du contenu au format markdown. Un séparateur (---) permet de distinguer les deux parties.

```
titre: Mon premier article
auteur: Bertil Chapuis
date: 2021-03-10
---
# Mon premier article
## Mon sous-titre
Le contenu de mon article.
![Une image](./image.png)
```

## Taches
- [x] documenter ses choix dans le portfolio
- [x] l'issue #22 a besoin d'un fichier "index.md" pour le copier avec sa commande. Ce fichier doit correspondre (dans son format) à l'exemple ci-dessus
- [x] Ce fichier dois se trouver dans un package "init"

## Estimation du temps de développement 
| optimiste 🎉 | attendu 🌮  | pessimiste 💩 |
|:---------------:|:--------------:|:---------------:|
|  5 minutes | 10 minutes | 15 minutes |

**Comment by chloefont** [comment]
Temps pris : 00:08:11
