### ISSUE TITLE
Initialiser un site statique

### ISSUE THREAD

**Issue by LucaCoduriV** [dil-classroom/projet-coduri_fontaine_grunder_jeanrenaud#22]
En tant qu’utilisateur, j’aimerais exécuter la commande suivante de manière à initialiser un site statique dans le
dossier /mon/site.
$ statique init /mon/site
En d’autres termes, la sous-commande init pourrait créer ou enrichir le dossier nommé /mon/site avec un fichier
de configuration config.yaml contenant des informations générales liées au site (titre, description, domaine, etc.) et
un fichier Markdown index.md contenant une page d’accueil avec des métadonnées et du contenu.

## Taches
- [ ] documenter ses choix dans le portfolio
- [ ] Utiliser picocli pour créer, dans le dossier désigné par le paramètre de la commande, les fichiers : "config.yaml" et "index.md"
- [ ] Le fichier "index.md" doit déjà avoir du contenu exemple qui correspond aux demandes de l'issue #20  
- [ ] Le fichier "config.yaml" doit déjà avoir des configuration de base "exemple". Du coup il faut créer un tel fichier qui sera copier par cette commande.
- [ ] Les exemples qu'elle doit copier doivent se trouver dans un dossier "init".

## Estimation du temps de development
| optimiste 🎉 | attendu 🌮  | pessimiste 💩 |
|:---------------:|:--------------:|:---------------:|
|  30 minutes | 1 heure | 2 heure |

**Comment by A-Grunder** [comment]
Effective time worked on : approx.. 3 hours
