### ISSUE TITLE
Release et documentation

### ISSUE THREAD

**Issue by chloefont** [dil-classroom/projet-coduri_fontaine_grunder_jeanrenaud#23]
En tant que développeur, j’aimerais qu’une release du générateur de site statique soit téléchargeable depuis l’onglet
release de GitHub. Un tag git (v0.0.1) correspondant à la release doit être publié. La release doit également être
accompagnée d’instructions d’installation reproductibles.

## Taches
- [ ] documenter ses choix dans le portfolio
- [ ] Trouver comment utiliser release de GitHub
- [ ] Mettre en place une release avec de nom de version pertinent

## Estimation du temps de development
| optimiste 🎉 | attendu 🌮  | pessimiste 💩 |
|:---------------:|:--------------:|:---------------:|
|  20 minutes | 40 minutes | 1 heure |

**Comment by A-Grunder** [comment]
A été complété grace à #35
