### ISSUE TITLE
Serveur HTTP

### ISSUE THREAD

**Issue by chloefont** [dil-classroom/projet-coduri_fontaine_grunder_jeanrenaud#34]
En tant qu’utilisateur, j’aimerais exécuter la commande suivante de manière à pouvoir visualiser le résultat de la
compilation du site Internet dans un navigateur Web.

```
$ statique serve /mon/site
```

## Tâches
- [x] documenter ses choix dans le portfolio
- [x] démarrer un serveur HTTP
- [x] servir le dossier précisé en ligne de commande

## Estimation du temps de développement
| optimiste 🎉 | attendu 🌮  | pessimiste 💩 |
|:---------------:|:--------------:|:---------------:|
| 30 min| 1 heure | 2 heures | 
Temps réel : 5h

**Comment by LucaCoduriV** [comment]
Voici un tuto sur comment créer un serveur http facilement et servir un répertoire http://rememberjava.com/http/2017/01/20/simple_http_server.html
