### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by chloefont** [dil-classroom/projet-coduri_fontaine_grunder_jeanrenaud#63]
Configurez Jacoco7 ou un outil équivalent pour calculer le degré de couverture de votre code par des tests unitaires et
d’intégration. Ajoutez les données de couverture à votre rapport.

## Tâches
- [x] documenter ses choix dans le portfolio

## Estimation du temps de développement
| optimiste 🎉 | attendu 🌮  | pessimiste 💩 |
|:---------------:|:--------------:|:---------------:|
| 1 heure | 2 heure | 3 heures |

**Comment by LucaCoduriV** [comment]
https://github.com/marketplace/actions/jacoco-report
